### ISSUE TITLE
gfx803 测试可用，但不稳定

### ISSUE THREAD

**Issue by woodcoal** [likelovewant/ollama-for-amd#1]
### What is the issue?

感谢提供这个 amd 版本，老卡已经可以使用了。

我的卡是 AMD Radeon(TM) Pro Duo，想过很多办法都没法正常运行，只有你的方案目前还可以运行。

但是还是存在几个奇怪的问题：
1. 挑模型，大部分模型无法正常启动，报 llama runner process has terminated: exit status 0xc0000005 错误。能运行的小部分模型偶尔多跑几次也会出现类似错误。
2. 能运行的模型比如：yi:9b 响应相当慢，要等待 10-60 秒不等才输出结果，但是输出结果的时候速度又正常。

我是用 llama.cpp 提供各种 adm 卡解决方案，好像也都不正常，唯独 win-vulkan-x64 的方案跑成功过一两次，速度内存占用都很正常。

我调试很多次，发现很大原因应该是说内存不可读，我这是 16 * 2 的卡，理论上不会存在这些问题，但是就是很奇怪。

不知道针对 gfx803 有没有更完美一点的解决办法，谢谢了。

### OS

Windows

### GPU

AMD

### CPU

Intel

**Comment by likelovewant** [comment]
可以测试 选项 1 ：[gfx803]( https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/blob/main/rocblas%20for%20gfx803%20(override%20with%20vega10).7z )  or 2: 另一作者 rocm (https://www.bilibili.com/read/cv34438089/?jump_opus=1) (有人反馈据说可用），查看了一下他编译的文件，缺少一些主要内容。但可以测试是否可用

**Comment by likelovewant** [comment]
> 可以测试 选项 1 ：[gfx803](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/blob/main/rocblas%20for%20gfx803%20(override%20with%20vega10).7z) or 2: 另一作者[ rocm ](https://www.bilibili.com/read/cv34438089/?jump_opus=1) (有人反馈据说可用），查看了一下他编译的文件，缺少一些主要内容。但可以测试是否可用

**Comment by likelovewant** [comment]
> ### What is the issue?
> 感谢提供这个 amd 版本，老卡已经可以使用了。
> 
> 我的卡是 AMD Radeon(TM) Pro Duo，想过很多办法都没法正常运行，只有你的方案目前还可以运行。
> 
> 但是还是存在几个奇怪的问题：
> 
> 1. 挑模型，大部分模型无法正常启动，报 llama runner process has terminated: exit status 0xc0000005 错误。能运行的小部分模型偶尔多跑几次也会出现类似错误。
> 2. 能运行的模型比如：yi:9b 响应相当慢，要等待 10-60 秒不等才输出结果，但是输出结果的时候速度又正常。
> 
> 我是用 llama.cpp 提供各种 adm 卡解决方案，好像也都不正常，唯独 win-vulkan-x64 的方案跑成功过一两次，速度内存占用都很正常。
> 
> 我调试很多次，发现很大原因应该是说内存不可读，我这是 16 * 2 的卡，理论上不会存在这些问题，但是就是很奇怪。
> 
> 不知道针对 gfx803 有没有更完美一点的解决办法，谢谢了。
> 
> ### OS
> Windows
> 
> ### GPU
> AMD
> 
> ### CPU
> Intel
> 
> ### Ollama version
> _No response_

可以测试 选项 1 ：[gfx803](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/blob/main/rocblas%20for%20gfx803%20(override%20with%20vega10).7z) or 2: 另一作者[ rocm ](https://www.bilibili.com/read/cv34438089/?jump_opus=1)(有人反馈据说可用），查看了一下他编译的文件，编译不完整，缺少一些主要内容。但有人反馈可用。可以测试是否可用

**Comment by woodcoal** [comment]
谢谢，还是一样，没有本质的区别。
问个问题要考虑1分钟才吐出结果，多执行几次连模型都启动不了，太奇怪了。

看样子这卡只能扔了 😂

**Comment by woodcoal** [comment]
zluda 试过，和那个问题说明的一样，试过 0.1.33 可以用，后续版本用不了。

其实本质问题是不论你用那种方式，虽然某些方法可以跑起来，但是每次都需要等差不多一分钟才开始给答案。
相比我直接跑 CPU 速度快不了多少了，最起码的 CPU 跑的时候立马就可以蹦出结果。

就好比1分钟可以解决的事情，它每次要预热1分多钟才开工。人家 CPU 也是2分钟把问题解决了。这样给人的感觉就是我折腾了，结果还是鸡肋。

**Comment by likelovewant** [comment]
虽然....但是.... 这速度确实不值得。 如果没有其他的保密要求。可以直接使用 qroq 的api，找个前端如 jan ai ，开启科学，可以直接用llama3 70b，速度飞快。

**Comment by woodcoal** [comment]
谢谢，目前也能这样了。待下次再去研究下 linux  下情况如何

**Comment by likelovewant** [comment]
查看gfx803 的原始 logic [文件]( https://github.com/ROCm/rocBLAS/tree/develop/library/src/blas3/Tensile/Logic/asm_full/r9nano), 你会发现他这个文件支持的功能很少， 只有SB和DB 两个类型的文件。如果想要探索和解决这个官方都不在继续支持的卡，可以尝试根据这个[说明](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/wiki/Tensile-tuning-Guide)去重新生成logic 文件, 然后重新编译 rocblas. ( 请自行右键一键翻译为中文）这个方法耗时较多 需要大约一周的时间，如果要跑通的话，且只能在自己的显卡上生成。生成后的文件或许可以共享给其他的gfx803 显卡使用，请自行体验。 @woodcoal

**Comment by jcleng** [comment]
gfx803能跑的,配合[rocblas](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7), 偶尔出现` llama runner process has terminated: exit status`, 重启Ollama即可, 只要Ollama预热了, 连续跑几天也没有问题; 用的qwen2:7b, 差不多1-2分钟一篇长文本,我觉得很正常(接百度的私有化api也是这个速度).
![图片](https://github.com/user-attachments/assets/055b1854-9d7f-4edc-90f9-9f5ba6228ec9)

**Comment by PhDLuffy** [comment]
> gfx803能跑的,配合[rocblas](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7), 偶尔出现` llama runner process has terminated: exit status`, 重启Ollama即可, 只要Ollama预热了, 连续跑几天也没有问题; 用的qwen2:7b, 差不多1-2分钟一篇长文本,我觉得很正常(接百度的私有化api也是这个速度). ![图片](https://private-user-images.githubusercontent.com/13532265/351548119-055b1854-9d7f-4edc-90f9-9f5ba6228ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTIyNzUsIm5iZiI6MTcyMzA5MTk3NSwicGF0aCI6Ii8xMzUzMjI2NS8zNTE1NDgxMTktMDU1YjE4NTQtOWQ3Zi00ZWRjLTkwZjktOWY1YmE2MjI4ZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZjhjZTZlNWJjODY2MGQ2YmRhNTU2NmQ3YmZkODYyOGI4NWI2Nzg5MDU3OTY1OTU0NGE2YjQ5NzM0YTdmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lB68GaMxRE_HlQTiDcdUCckUHVYoiOwnklOjt0CzqUw)

你好，请问下方面发一份rx580的ollama-setup安装程序么？我自己电脑不会搞编译。

我也是rx580雷电显卡坞

**Comment by jcleng** [comment]
> > gfx803能跑的,配合[rocblas](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7), 偶尔出现` llama runner process has terminated: exit status`, 重启Ollama即可, 只要Ollama预热了, 连续跑几天也没有问题; 用的qwen2:7b, 差不多1-2分钟一篇长文本,我觉得很正常(接百度的私有化api也是这个速度). ![图片](https://private-user-images.githubusercontent.com/13532265/351548119-055b1854-9d7f-4edc-90f9-9f5ba6228ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTIyNzUsIm5iZiI6MTcyMzA5MTk3NSwicGF0aCI6Ii8xMzUzMjI2NS8zNTE1NDgxMTktMDU1YjE4NTQtOWQ3Zi00ZWRjLTkwZjktOWY1YmE2MjI4ZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZjhjZTZlNWJjODY2MGQ2YmRhNTU2NmQ3YmZkODYyOGI4NWI2Nzg5MDU3OTY1OTU0NGE2YjQ5NzM0YTdmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lB68GaMxRE_HlQTiDcdUCckUHVYoiOwnklOjt0CzqUw)
> 
> 你好，请问下方面发一份rx580的ollama-setup安装程序么？我自己电脑不会搞编译。
> 
> 我也是rx580雷电显卡坞

用的这个[https://github.com/likelovewant/ollama-for-amd/releases/tag/v0.3.2](https://github.com/likelovewant/ollama-for-amd/releases/tag/v0.3.2)

**Comment by PhDLuffy** [comment]
> > > gfx803能跑的,配合[rocblas](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7), 偶尔出现` llama runner process has terminated: exit status`, 重启Ollama即可, 只要Ollama预热了, 连续跑几天也没有问题; 用的qwen2:7b, 差不多1-2分钟一篇长文本,我觉得很正常(接百度的私有化api也是这个速度). ![图片](https://private-user-images.githubusercontent.com/13532265/351548119-055b1854-9d7f-4edc-90f9-9f5ba6228ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTIyNzUsIm5iZiI6MTcyMzA5MTk3NSwicGF0aCI6Ii8xMzUzMjI2NS8zNTE1NDgxMTktMDU1YjE4NTQtOWQ3Zi00ZWRjLTkwZjktOWY1YmE2MjI4ZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZjhjZTZlNWJjODY2MGQ2YmRhNTU2NmQ3YmZkODYyOGI4NWI2Nzg5MDU3OTY1OTU0NGE2YjQ5NzM0YTdmNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lB68GaMxRE_HlQTiDcdUCckUHVYoiOwnklOjt0CzqUw)
> > 
> > 
> > 你好，请问下方面发一份rx580的ollama-setup安装程序么？我自己电脑不会搞编译。
> > 我也是rx580雷电显卡坞
> 
> 用的这个https://github.com/likelovewant/ollama-for-amd/releases/tag/v0.3.2

多谢，可以正常调用RX580了，速度比CPU块很多。

但是我看任务管理器里面的显卡调用并没有显示占用程度，是否是显示BUG呢？

还有我的RX 580很明显调用的时候滋滋响，是啸叫还是怎么回事。。回答完之后就恢复正常了。

**Comment by jcleng** [comment]
@PhDLuffy 是的, 看显存占用
