### ISSUE TITLE
3.0 for AMD got runtime error

### ISSUE THREAD

**Issue by jyung-hk** [likelovewant/ollama-for-amd#11]
### What is the issue?

Hi, ollama serve starts successfully and able to detect gfx1035 with rocm files installed . However when I pull any models, it returns this message 

[GIN] 2024/07/27 - 01:35:57 | 200 |            0s |       127.0.0.1 | HEAD     "/"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x7ff78fa5b656]

goroutine 25 [running]:
github.com/ollama/ollama/server.makeRequest({0x7ff7901203d0, 0xc000094af0}, {0x7ff78ff77925, 0x3}, 0x7ff78fe267a0?, 0xc000520510, {0x0, 0x0}, 0x0)
        github.com/ollama/ollama/server/images.go:1137 +0x476
github.com/ollama/ollama/server.getAuthorizationToken({0x7ff7901203d0, 0xc000094af0}, {{0xc0000375ee, 0x23}, {0xc00003761c, 0x6}, {0xc00003762b, 0x1}})
        github.com/ollama/ollama/server/auth.go:70 +0x438
github.com/ollama/ollama/server.makeRequestWithRetry({0x7ff7901203d0, 0xc000094af0}, {0x7ff78ff77925, 0x3}, 0xc000199440, 0xc000520870, {0x0, 0x0}, 0xc0006a0000)
        github.com/ollama/ollama/server/images.go:1065 +0x1cf
github.com/ollama/ollama/server.pullModelManifest({0x7ff7901203d0, 0xc000094af0}, {{0x7ff78ff79492, 0x5}, {0x7ff78ff8d937, 0x12}, {0x7ff78ff81db8, 0x7}, {0xc00042a000, 0xa}, ...}, ...)

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

3.0

**Comment by likelovewant** [comment]
**Before Proceeding:**

* **ROCm Support and HIPSDK:** Ensure you have ROCm support properly configured and that you've installed HIPSDK
version 5.7.

* **Troubleshooting:** If, after confirming these prerequisites, the issue persists, consider trying an earlier
version of Ollama (v0.2.7). Versions v0.2.8 and v0.3.0 have reportedly experienced download issues for some users.

**Comment by jyung-hk** [comment]
Hi, thanks for reply. Both 027 and 028 are working fine. Sent from my iPhoneOn 27 Jul 2024, at 2:00 AM, likelovewant ***@***.***> wrote:﻿
Before Proceeding:


ROCm Support and HIPSDK: Ensure you have ROCm support properly configured and that you've installed HIPSDK
version 5.7.


Troubleshooting: If, after confirming these prerequisites, the issue persists, consider trying an earlier
version of Ollama (v0.2.7). Versions v0.2.8 and v0.3.0 have reportedly experienced download issues for some users.

**Comment by likelovewant** [comment]
You're welcome! I'm happy to hear that both version 0.27 and 0.28 are working well for you.  also the v0.3.0 was reupload .

**Comment by jyung-hk** [comment]
Hi, I downloaded and reinstalled the new 030, seems working now. Thanks.
