### ISSUE TITLE
打包制品7z可能有问题

### ISSUE THREAD

**Issue by wszgrcy** [likelovewant/ollama-for-amd#13]
### What is the issue?

首先感谢大佬
今天使用时首先下载的时7z，然后按照说明把1103的相关文件都复制进去了，然后测试qwen2:0.5正常7b就乱码
https://github.com/likelovewant/ollama-for-amd/issues/12
找了一圈后改为exe的那个，结果发现exe的安装后竟然正常，通过比对后发现
![image](https://github.com/user-attachments/assets/5962d22c-4d5a-44f7-bb77-9d851680bfc5)
当我把这个ggml.dll的文件替换过后7z解压的也正常了，请问下大佬是不是打包的制品有什么区别？还是下载或者解压的时候损坏了

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.0

**Comment by likelovewant** [comment]
由于这个版本更新和上传了多次。以为没有人用打包文件，且由于网络原因。就没有上传。已更新

**Comment by wszgrcy** [comment]
> 由于这个版本更新和上传了多次。以为没有人用打包文件，且由于网络原因。就没有上传。已更新

感谢,我以为是流水线自动出来的有啥问题呢

**Comment by likelovewant** [comment]
ok ，网络上传问题。感谢反馈。
