### ISSUE TITLE
AMD Ryzen 7 8845HS w/ Radeon 780M

### ISSUE THREAD

**Issue by goukisun** [likelovewant/ollama-for-amd#18]
### What is the issue?

use ollama-windows-amd64.7z, it report 0xc0000005 error.
thx to this issue, now it can work.
https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/issues/8
copy all *.dll to runner/rocm6.1
copy rocblas folder to runner/rocm6.1
now it's a bit practical。 with Qwen2 7B， 17 tokens/s， and in LM studio is 10 tokens/s
thanks for you work

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.30.0

**Comment by likelovewant** [comment]
OllamaSetup.exe  should be better .otherwise , https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/issues/8 is an alternative .
