### ISSUE TITLE
【MAYBE BUG】About "llama runner process has terminated: exit status 0xc0000005"

### ISSUE THREAD

**Issue by ByronLeeeee** [likelovewant/ollama-for-amd#19]
### What is the issue?

为了方便描述，我直接用中文了。

某次重启（也许是安装了系统补丁）后，3.10版无论Run哪个模型都会提示"llama runner process has terminated: exit status 0xc0000005"

经过重启、重装该库的Ollama、重装HIP 6.12、升级AMD驱动、重新覆盖rocblas等做法后，仍无法解决，不能成功载入模型。

搜索后在[ROCmLibs-for-gfx1103-AMD780M-APU/issues/8](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/issues/8)获得了解决灵感。

通过把 `AppData\Local\Programs\Ollama\lib\ollama` 内的全部`*.dll`文件，连同`rocblas`文件夹一并复制到`AppData\Local\Programs\Ollama\lib\ollama\runners\rocm_v6.1`后，问题解决，无论Run模型还是POST都能成功获取response。

感觉是rocm_v6.1目录下的`ollama_llama_server.exe`无法读取`\lib\ollama`的相关文件导致的。

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.10

**Comment by ByronLeeeee** [comment]
补充：

680M（6800H）遇到了这个问题，另一台5700XT（环境变量手动改1030）没有遇到同样的问题。

**Comment by likelovewant** [comment]
根据目前的反馈包括ollama issue section，主要问题大致出现在驱动文件的amdhip64_6.dll， 并未集成在安装包中，主要由驱动程序提供。由于更新了6.1，需要依赖于这个驱动，而5.7 依赖于amdhip64.dll， 这个驱动会自动匹配识别，但是amdhip64_6.dll 这个存在许多版本，且会时不时自动匹配到amdhip64.dll，导致版本匹配错误，无法准确的识别或准确翻译程序内容。需要amd 调整驱动或ollama 匹配新的补丁。且待官方更新

**Comment by ginisksam** [comment]
Am having same problems... RT 6700 using Optimized_ROCmLibs_gfx1031 library

**Comment by likelovewant** [comment]
> Am having same problems... RT 6700 using Optimized_ROCmLibs_gfx1031 library

English version available at https://github.com/likelovewant/ollama-for-amd/issues/18

**Comment by likelovewant** [comment]
should be able to work in latest release .otherwise ,the copy .dll method still works
