### ISSUE TITLE
gfx903的rocBLAS可以也编译一下么

### ISSUE THREAD

**Issue by sakfire** [likelovewant/ollama-for-amd#2]
已经有gfx902和gfx904的rocblas.dll了，唯独没有gfx903的，903是否也支持呢，如果支持，能否也编译一份。非常感谢！

**Comment by likelovewant** [comment]
windows版本的hip sdk 5.7.3，runtime 不支持 gfx903，如需支持，需要重新编译rocm的 runtime 。然后再编写，否则无法成功编译。只是runtime 在windows 下是闭源，耗时较多。没有详细的踩坑过程，耗时耗力，不值得。
