### ISSUE TITLE
v0.3.8 and v0.3.10 don't detect gfx1103 (AMD RadeonT 780M)

### ISSUE THREAD

**Issue by orajson** [likelovewant/ollama-for-amd#20]
### What is the issue?

v0.3.8 and v0.3.10 don't detect gfx1103 (AMD RadeonT 780M) but still using CPU
![image](https://github.com/user-attachments/assets/436c5978-0c2e-4c4c-9dd4-b45fc45dd1bf)
However v0.3.6 detects gfx1103 and uses GPU well
![image](https://github.com/user-attachments/assets/77661407-39c7-47b6-aefc-3b3f65cdee9d)

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.8, 0.3.10

**Comment by likelovewant** [comment]
That's a bug relate to drivers /amdhip64_6.dll which support rocm6.1.2 some drivers can not pick it up . and there are several version of it . make sure get the latest drivers . and try the solution https://github.com/likelovewant/ollama-for-amd/issues/18

**Comment by orajson** [comment]
I followed the steps in the bug but didn't help. 
Please advise if I have missed something from below steps

1. Download ollama-windows-amd64.7z from https://github.com/likelovewant/ollama-for-amd/releases/tag/v0.3.11
2. unzip the file in "C:\Program Files\ollama"
3. Move all "C:\Program Files\ollama\lib\ollama\*.dll" to "C:\Program Files\ollama\lib\ollama\runners\rocm_v6.1\"
4. Move a folder "C:\Program Files\ollama\lib\ollama\rocblas" to "C:\Program Files\ollama\lib\ollama\runners\rocm_v6.1\"
5. So now I have all *.dll and rocblas folder moved in "C:\Program Files\ollama\lib\ollama\runners\rocm_v6.1\"
6. Execute "C:\Program Files\ollama\ollama.exe serve" to start ollama server

FYI, I have HIP SDK 6.1.0 installed on my Windows 11 and HIP_PATH, HIP_PATH_61 environment variable configured

**Comment by likelovewant** [comment]
1,The directory is in `C:\Users\usrname\AppData\Local\Programs\Ollama\`: rather than  `"C:\Program Files\ollama\`
2, it's recommend to install or update ollama via `OllamaSetup.exe` rather than `ollama-windows-amd64.7z` since 
3, make sure you had latest drivers also.

**Comment by orajson** [comment]
Thanks for your assistance and now my issue is resolved after updating with latest AMD Driver. v0_3_11 uses gfx1103 now
