### ISSUE TITLE
Intel Mac AMD GPU

### ISSUE THREAD

**Issue by TomDev234** [likelovewant/ollama-for-amd#23]
Can you add support for Intel Macs with Metal3 AMD GPUs?

**Comment by likelovewant** [comment]
This fork depends on upstream ollama code, only add a few lines to support gpu list for windows as the official can not make it happen duo to lack of rocm libs for windows . while the linux and Mac may have a possible solution from upsteam ollama . if you can not utilized AMD GPUS on Macs via upstream ollama , you may refer to the some solution available at https://github.com/ollama/ollama/issues/1016 or simply build from source. [llama.cpp](https://github.com/ggerganov/llama.cpp/blob/master/docs/build.md#metal-build), have seens bunch of success cases if you can not  make it run via  ollama darwin release.

**Comment by likelovewant** [comment]
no local machine to test it and no response . closed it now.
