### ISSUE TITLE
Didn't use GPU

### ISSUE THREAD

**Issue by LaoDi-Sama** [likelovewant/ollama-for-amd#28]
### What is the issue?

First of all, i'm not sure if it's a bug but it can't use My GPU (RX 6600) with HIP 5.7
![image](https://github.com/user-attachments/assets/452b36d6-9f72-4bfc-beae-72eefde4441f)
Model is the Llama3 
without docker
if it isn't bug, please tell me how to made it correctly

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.1 from releases

**Comment by likelovewant** [comment]
Make sure intall the setup.exe installer first , it's breaking changes , simply 7z files replacement don't work. replace libs with rocmlibs for v5.7. also update drivers .

**Comment by LaoDi-Sama** [comment]
how to replace libs , witch libs and where?

**Comment by likelovewant** [comment]
> how to replace libs , witch libs and where?
> 
> 

Please check the release notes and wiki. @LaoDi-Sama

**Comment by CHN-STUDENT** [comment]
@LaoDi-Sama @likelovewant  hey, bro, i have RX 6600 too,i have question because of my poor english when try to read and follow wiki, so you mean i need to download hip driver and installed it then replace libs, installed special ollama. then use special version libs too? Could you give me some advice? thanks!

**Comment by likelovewant** [comment]
> @LaoDi-Sama @likelovewant  hey, bro, i have RX 6600 too,i have a question because of my poor english when try to read and follow wiki, so you mean i need to download hip driver from amd official website and installed the offical driver. Then i need to  replace libs, try to install special ollama. use special version libs too? Could you give me some advice? thanks!

There is Chinese version available at [bilibili](【AMD显卡全系列解锁Ollama支持，llama3运行更优雅！-哔哩哔哩】 https://b23.tv/kyrmqlX) maybe a little bit different. However basic rule is same .

@CHN-STUDENT

**Comment by CHN-STUDENT** [comment]
Hi @likelovewant thanks for your help and your good project, i download the 6.12 HIP driver and your special ollama version, replace the special models driver. Now it seems work normally. Thanks again.

**Comment by LaoDi-Sama** [comment]
妈的怎么都是中国人

**Comment by CHN-STUDENT** [comment]
这个项目作者大大也是，他娘的可真是个天才，让真正的AMD YES了
