### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by Mythendros** [likelovewant/ollama-for-amd#3]

**Comment by likelovewant** [comment]
this repo serve as a example by add more gpu on windows , while linux has more easier way .
which has less steps than this repo on windows .and Ollama official supported it , by override thing to get running on everything . Their easier approach is using HSA_OVERRIDE_GFX_VERSION eg, export HSA_OVERRIDE_GFX_VERSION=11.0.0 override with support gpu. then running ` Ollama run llama3 ` . more support information ,you will find in the Ollama official discord .try search your answer from the discord history chat , there has many solution over there.
