### ISSUE TITLE
May I ask if it is still possible to provide the ollama file for ROCm5.7

### ISSUE THREAD

**Issue by qixidao** [likelovewant/ollama-for-amd#31]
My graphics card is AMD 5700XT (gfx1010: xnack -),
I found that some models are not supported in 6.1.2 mode, but switching to 5.7 is normal.
I hope to continue releasing the program for ollama5.7
![QQ图片20241127152106](https://github.com/user-attachments/assets/4f0faec6-0979-44a8-904f-891cb0295786)

**Comment by qixidao** [comment]
> Sure,if there is still needed .Could you share your info which rocmlibs you are using for 5.7 . and the models not support in 6.1.2.

Thank you!
I don't know how to describe this problem. 
In this model, Llama3.2，
The same model can run normally with a load of 5.7, 
and it can also run normally with a load of 6.12, 
but it doesn't utilize the graphics card for processing when running, resulting in very slow speed
Other models don't have this issue.
That's why I hope to continue providing the 5.7 compiled version of ollama

**Comment by likelovewant** [comment]
Have noticed some issues with ROCm 6.12, particularly when upgrading from version 5.7. Some users report that
models only load partially onto the graphics card, with the other half using shared memory. This can significantly
slow down performance. **Reinstalling your drivers may help resolve this issue.** . Had included ROCm 5.7 in recent releases.
Thanks for your sharing . This information is really helpful when deciding on future builds!
