### ISSUE TITLE
WIKI中关于构建的指引建议增加需要安装Strawberryperl

### ISSUE THREAD

**Issue by ByronLeeeee** [likelovewant/ollama-for-amd#4]
昨晚为了使用GLM4，我尝试了一下按WIKI自行构建，但最新的MinGW-w64也会提示缺少头文件。

经测试，用Strawberryperl作为默认构建编译器就可以顺利完成构建。

因此，WIKI的Build指引建议换成这个链接：[https://github.com/ollama/ollama/blob/main/docs/development.md#windows](url)

并提示需要安装[Strawberry Perl](https://strawberryperl.com/)，且把Strawberry Perl设置为默认编译器（更改系统变量Path顺序）。

**Comment by likelovewant** [comment]
感谢建议。 已更新build 链接。strawberry perl 系统变量设置非必须。各人环境设置也会影响编译。日后确定后再做备注。

**Comment by ByronLeeeee** [comment]
> 感谢建议。 已更新build 链接。strawberry perl 系统变量设置非必须。各人环境设置也会影响编译。日后确定后再做备注。

此前编译过程，传统版MinGW提示缺少intrin.h，MinGW-w64提示
```
ninja: build stopped: subcommand failed.
llm\generate\generate_windows.go:3: running "powershell": exit status 1
```
理论也可能与我VS2022社区版没有Ninja有关。

Strawberry perl自带Ninja且会把Ninja放到Path中，可能会更有助于编译流程。

这可能也是官方AMD版编译教程[AMD版编译教程](https://github.com/ollama/ollama/blob/main/docs/development.md#windows-rocm-amd-radeon)建议安装的原因。

**Comment by likelovewant** [comment]
这也是一个原因，初次编译环境设置问题，通常会遇到许多“未解之谜”，已按照建议，更新了提醒。
