### ISSUE TITLE
exe with latest release 

### ISSUE THREAD

**Issue by RichardBosworth** [likelovewant/ollama-for-amd#5]
Hi,

Could we get a build exe with the latest release? I'm struggling to build from source (something about a "null array").

Thanks. Really appreciate the work so far. So much quicker on iGPU 780M vs CPU.

**Comment by likelovewant** [comment]
updated .

**Comment by likelovewant** [comment]
> Hi,
> 
> Could we get a build exe with the latest release? I'm struggling to build from source (something about a "null array").
> 
> Thanks. Really appreciate the work so far. So much quicker on iGPU 780M vs CPU.

@RichardBosworth , new released version available .

**Comment by RichardBosworth** [comment]
Great! Thanks so much. 

Do we need to update via usual Ollama download before installing this? (Download file sizes seem smaller on this) Or can we just install directly from the builds here without needing to update Ollama from CPU version?

**Comment by RichardBosworth** [comment]
Hi,

Also the new version appears to be running models on the CPU only (780M)?

Thanks

**Comment by likelovewant** [comment]
> Hi,
> 
> 
> 
> Also the new version appears to be running models on the CPU only (780M)?
> 
> 
> 
> Thanks

Simply download here and install it. If you have new hip sdk 6.1.2 installed . It's may fall to cpu . Simply change the environment variation in hipcofig from 6.1 to 5.7 . Otherwise , it's not working

**Comment by likelovewant** [comment]
> Great! Thanks so much. 
> 
> 
> 
> Do we need to update via usual Ollama download before installing this? (Download file sizes seem smaller on this) Or can we just install directly from the builds here without needing to update Ollama from CPU version?

It's better not to clicked the update pop up information . Simply ignore it. Instead download the latest from this repo. The information over there serves as a reminder only.

**Comment by RichardBosworth** [comment]
> > Hi,
> > Also the new version appears to be running models on the CPU only (780M)?
> > Thanks
> 
> Simply download here and install it. If you have new hip sdk 6.1.2 installed . It's may fall to cpu . Simply change the environment variation in hipcofig from 6.1 to 5.7 . Otherwise , it's not working

Thanks! How do you change the env variation?

**Comment by likelovewant** [comment]
> Uninstalling the hip files allowed it to use the GPU again

Anyway. The method available on [wiki pages] (https://www.computerhope.com/issues/ch000549.htm) in demo release note parts. Use it , the next time you may try something else.
