### ISSUE TITLE
Can this version Ollama add feature about "disable autoupdate"

### ISSUE THREAD

**Issue by esverde** [likelovewant/ollama-for-amd#6]

**Comment by wsadaaa** [comment]
nice advice

**Comment by likelovewant** [comment]
"If you don't click the update button, it won't update automatically. The 'Restart to Update' note is just a
reminder if there are any available updates. " if remove the update message , you may not received any update reminder when the update available .

**Comment by likelovewant** [comment]
I removed the Ollama update functionality as suggested.  However, I couldn't entirely get rid of the reminder
that appears when you start up. There might be dependencies on that update system that could cause issues if I
disable it completely.  For now, just feel free to click whatever button you prefer – there are no automatic
updates running."

**Comment by likelovewant** [comment]
For now , the reminder also gone .
