### ISSUE TITLE
How do you get it running with a 5600xt?

### ISSUE THREAD

**Issue by AggressiveCombo** [likelovewant/ollama-for-amd#9]
### What is the issue?

I downloaded this version and succesfully installed a model (llama2) but it's running on the cpu only.)
I'm using a 5600xt, 24gb ram.
ollama version 0.28
I'm using a wsl environment to run ollama (ubuntu) in vscode, i'm using windows 11 as the base.
I checked the gpu list and it has the gfx1010
3800x is my cpu.

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.2.8

**Comment by likelovewant** [comment]
**Prerequisites:**

* **ROCm Libraries:** Ensure you have the necessary ROCm libraries installed, specifically `rocblibs` for
GFX1010:xnack-. You can check your installation by typing `hipinfo` in your terminal. It should display `gfx1010
with extra tail xnack-`.
* **HSA_OVERRIDE_GFX_VERSION:** If you encounter issues, try setting the environment variable
`HSA_OVERRIDE_GFX_VERSION=10.1.10`. (gfx1010)

**Steps:**

1.  **Refer to the wiki guide for detailed instructions:**
[wiki#demo-release-version](https://github.com/likelovewant/ollama-for-amd/wiki#demo-release-version)

2.  **Start the Ollama server:** Navigate to `C:\Users\usrname\AppData\Local\Programs\Ollama\` in your terminal
and run:
    ```bash
    ./ollama serve
    ```
3.  **Run a model:** In a separate terminal window, choose a model (e.g., `llama3.1`) and execute:
    ```bash
    ./ollama run llama3.1
    ```

 **Additional Tips:**

* Replace `usrname` with your actual username.
* Refer to the wiki guide for troubleshooting tips and specific instructions for your AMD GPU model.

**Comment by AggressiveCombo** [comment]
I figured it out. I used ollama version 0.27 and downloaded the demo release. I then replaced the files for rocm in the rocblas folder and it works now. thank you!

**Comment by likelovewant** [comment]
I'm glad you were able to figure it out and get it working. 

Let me know if you have any other questions or run into any more issues in the future. Good luck ! 👍
